# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Despliegue de aplicacion en vue CI

on:
  push:
    branches: [ "master" ]
  

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Echo the message
      run: |
        echo "Hola"        
    
